'use client'
import './globals.css'
import Head from 'next/head'
import Header from '@/components/shared/Header'
import { SessionProvider } from 'next-auth/react'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=general-sans@500,300,600,400&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <body>
        <SessionProvider>
          <main className="max-w-7xl mx-auto">
            <Header />
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
